# Generated by Django 5.1.4 on 2026-06-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planting', '0003_refactor_nivel_tecnologico'),
        ('properties', '0004_delete_weatherhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da máquina')),
                ('modelo', models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo')),
                ('categoria', models.CharField(choices=[('trator', 'Trator'), ('colheitadeira', 'Colheitadeira'), ('pulverizador', 'Pulverizador'), ('semeadora', 'Semeadora'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('horimetro_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Horímetro atual')),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo por hora (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='properties.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Máquina / Equipamento',
                'verbose_name_plural': 'Máquinas / Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], default='preventiva', max_length=20, verbose_name='Tipo de manutenção')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo (R$)')),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='planting.safra', verbose_name='Safra')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='operational.maquina', verbose_name='Máquina / Equipamento')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo_combustivel', models.CharField(max_length=50, verbose_name='Tipo de combustível')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (litros)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total (R$)')),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='planting.safra', verbose_name='Safra')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='operational.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('criterio', models.CharField(choices=[('data', 'Data'), ('horimetro', 'Horímetro')], default='data', max_length=20, verbose_name='Critério')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data limite')),
                ('horimetro_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro limite')),
                ('dias_alerta', models.IntegerField(default=15, verbose_name='Dias de antecedência para alerta')),
                ('horas_alerta', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Horas restantes de horímetro para alerta')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes', to='operational.maquina', verbose_name='Máquina')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes_manutencao', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Programação de Manutenção',
                'verbose_name_plural': 'Programações de Manutenção',
                'ordering': ['concluida', 'data_limite', 'horimetro_limite'],
            },
        ),
        migrations.CreateModel(
            name='UsoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora Fim')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas trabalhadas')),
                ('atividade', models.CharField(choices=[('plantio', 'Plantio'), ('pulverizacao', 'Pulverização'), ('adubacao', 'Adubação'), ('colheita', 'Colheita'), ('transporte', 'Transporte'), ('preparo_solo', 'Preparo de Solo'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Atividade')),
                ('operador', models.CharField(blank=True, default='', max_length=120, verbose_name='Operador')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='operational.maquina', verbose_name='Máquina')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_maquina', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_maquina', to='planting.safra', verbose_name='Safra')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_maquina', to='properties.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Uso de Máquina',
                'verbose_name_plural': 'Uso de Máquinas',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
