# Generated by Django 5.1.4 on 2026-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(choices=[('trator', 'Trator'), ('colheitadeira', 'Colheitadeira'), ('pulverizador', 'Pulverizador'), ('semeadora', 'Semeadora'), ('plantadeira', 'Plantadeira'), ('caminhao', 'Caminhão'), ('implemento', 'Implemento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='programacaomanutencao',
            name='criterio',
            field=models.CharField(choices=[('data', 'Data'), ('horimetro', 'Horímetro'), ('ambos', 'Ambos')], default='data', max_length=20, verbose_name='Critério'),
        ),
    ]
