# Generated by Django 5.1.4 on 2026-06-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planting', '0003_refactor_nivel_tecnologico'),
        ('properties', '0004_delete_weatherhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos'), ('combustivel', 'Combustível'), ('manutencao', 'Manutenção'), ('mao_de_obra', 'Mão de Obra'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('data', models.DateField(verbose_name='Data da Despesa')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='properties.propriedade', verbose_name='Propriedade')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='planting.safra', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=200, verbose_name='Comprador')),
                ('produto', models.CharField(max_length=150, verbose_name='Produto')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('sacas', 'Sacas'), ('kg', 'Kg'), ('tonelada', 'Tonelada'), ('outro', 'Outro')], default='sacas', max_length=20, verbose_name='Unidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total (R$)')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='properties.propriedade', verbose_name='Propriedade')),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='planting.safra', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_venda', '-created_at'],
            },
        ),
    ]
